name: Vercel Static Frontend Deployment

on:
  push:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_PROJECT_NAME: 'finesse-frontend'
  DEPLOYMENT_ENVIRONMENT: 'dev'

permissions:
    checks: read
    contents: read
    pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version-file: "package.json"

      - name: install npm
        run: npm install -g npm@9.8.1

      - name: Install Vercel CLI
        run: npm install vercel@latest

      - name: ENVFILE
        uses: alekangelov/secret-envfile@v1
        with:
          content: ${{ secrets.ENV }}
          filename: .env

      - name: List files
        run: ls -a

      - name: Push env variables to vercel
        uses: hackzcompany/vercel-env-push-action@v4
        with:
          project: ${{ env.VERCEL_PROJECT_NAME }}
          team_id: ${{ secrets.VERCEL_ORG_ID }}
          token: ${{ secrets.VERCEL_TOKEN }}
          environments: previews
          env_type: secret
          env_file: .env

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: echo "DEPLOYMENT_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_ENV

      - name: Set URL to dev environment
        run: vc alias "$DEPLOYMENT_URL" ${{ env.VERCEL_PROJECT_NAME }}-${{ env.DEPLOYMENT_ENVIRONMENT }}.vercel.app --token=${{ secrets.VERCEL_TOKEN }}
