name: Vercel Preview Deployment

on:
  push:
  pull_request:

jobs:

  lint-test:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-lint-test-node.yml@main

  vercel-deployment-dev:
    needs: lint-test
    uses: ai-cfia/github-workflows/.github/workflows/workflow-vercel-deployment.yml@60-vercel-deployment-workflow-only-comments-the-url-of-the-most-recent-build
    with:
        project-name: 'finesse-frontend'
        deployment-environment: 'dev'
    secrets: inherit

  vercel-deployment-uat:
    if: github.ref == 'refs/heads/main'
    uses: ai-cfia/github-workflows/.github/workflows/workflow-vercel-deployment.yml@60-vercel-deployment-workflow-only-comments-the-url-of-the-most-recent-build
    with:
        project-name: 'finesse-frontend'
        deployment-environment: 'uat'
    secrets: inherit
